Real homework
JaehoonSong12/ydjs_academic pull request #23
Opened 2024-12-17 02:01 UTC by okggff

I finished my homework for problems #6 (factoring) and #13 (triangle inequality theorem). let me know if you have any problems. I will continue the homework tomorrow!

2024-12-17 04:41 UTC, JaehoonSong12 requested changes
Review has been done, see the `files changed` section to see the details.

Modify majority of the context, you are supposed to write-up feedback short but practical, not textbook-like paragraphs.

2024-12-17 04:41 UTC, JaehoonSong12 commented on docs/JAYDEN.md
> +- [📐 Triangle Inequality Theorem](#-triangle-inequality-theorem)
do not use these icons, it makes the content hard to read.

2024-12-17 04:41 UTC, JaehoonSong12 commented on docs/JAYDEN.md
> +  - [📝 Why is this True?](#-why-is-this-true)
Titles are not aligned by their importance level.

Why is "Triangle Inequality Theorem" heading level 1? it does not have consistency with the other topic, "absolute value".

2024-12-17 04:41 UTC, JaehoonSong12 commented on docs/JAYDEN.md
> +  - [🎯 What is the Triangle Inequality Theorem?](#-what-is-the-triangle-inequality-theorem)
For headings, use short, but descriptive nouns, not sentences.

Headers are supposed to be less then 3 words, sometimes with parentheses. ()

2024-12-17 04:41 UTC, JaehoonSong12 commented on docs/JAYDEN.md
> +![Triangle Inequality Theorem](./images/Triangle-Inequality-Theorm.webp)
This image is not conceptual, it is not a presentation.

Be more practical.

2024-12-17 04:41 UTC, JaehoonSong12 commented on docs/JAYDEN.md
> +- ✅ **a + b > c**
Too many boldfaced words, boldface must be used a few times to highlight important contexts, not everywhere.

2024-12-19 01:34 UTC, closed without merging

2024-12-19 01:40 UTC, okggff commented
I'm can't git02-branch+push.sh the fixed homework

2024-12-19 02:12 UTC, okggff commented
I  git02-branch+push.sh my homework, but I can't remember next step.

2024-12-19 02:14 UTC, okggff commented
and I can't see my fixed homework anywhere in github

2024-12-19 03:48 UTC, JaehoonSong12 commented
Things to remember
#1: do not rush, if you cannot figure something out, write-up about the situation with a single reply
#2: do not delete the branches that contains all your work. Seat back and wait for my response.

I will revert the branch deletion, once you pull everything, manually type in the following command to work on your feedback!
`git checkout Real_Homework`

2024-12-19 12:47 UTC, okggff commented
I pulled and `git checkout Real_Homework`. Should I create a new branch to push my homework after it's finished?

2024-12-19 12:52 UTC, JaehoonSong12 commented
Up to you! You are all set at the point!

2024-12-20 01:02 UTC, okggff commented
Alright!, and since I can't bring my desktop to Korea, I can't do my desktop related homework, so I can only do paper homework.